apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-broker
  namespace: message-hub
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: message-broker
    spec:
      containers:
      - name: message-broker
        image: rmohr/activemq:latest
        ports:
        - containerPort: 8161
        - containerPort: 61616
        
---   
apiVersion: v1
kind: Service
metadata:
  name: message-broker-service
  namespace: message-hub
spec:
  type: NodePort
  selector:
    app: message-broker
  ports:
  - name: web-front-end
    protocol: TCP
    port: 8161
    targetPort: 8161
  - name: messaging-clients
    protocol: TCP
    port: 61616
    targetPort: 61616